#docker-compose.yml
#version: "3.5"
version: "2"

services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=habits
    restart: always
    ports:
      - "5434:${DB_PORT}"
    volumes: [ './postgresql_db/db/:/var/lib/postgresql_db/data/', './postgresql_db/db/:/logs/' ]
#    command: ["postgres", "-c", "log_destination=stderr", "-c", "logging_collector=on", "-c", "log_directory=/logs", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    command: ["postgres", "-c", "log_statement=all"]
    expose:
      - 5434
    networks:
      app_fastapi_network:
        ipv4_address: 192.168.55.4

  app:
    build: .
    container_name: fastapi
    stop_signal: SIGKILL
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      app_fastapi_network:
        ipv4_address: 192.168.55.5


networks:
  app_fastapi_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
